# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f792a81f18148800983ac534df4382d707320c6acc402c41e9bb71e397ce75313e7f073eb09cafeacc8c52e24765d5ef57bf08a46082b97056f2b29a198d9d1

test:
  secret_key_base: f89037eca6b7554c259d208a560594926629e58c5fb104ec030c8fca02223e9a6f999a615a8870b6bc4f93e70c173fa284ff70b1183ecdf6ac2461c0d78d06be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
